### ISSUE TITLE
failed run on macos; throw InvalidOperationException

### ISSUE THREAD

**Issue by gaozhou** [ikpil/DotRecast#1]
program = _gl.CreateProgram();
uint vert_shdr = _gl.CreateShader(GLEnum.VertexShader);
_gl.ShaderSource(vert_shdr, vertex_shader);
_gl.CompileShader(vert_shdr);
_gl.GetShader(vert_shdr, GLEnum.CompileStatus, out var status);
if (status != (int)GLEnum.True)
{
    throw new InvalidOperationException();
}

**Comment by ikpil** [comment]
I was delayed in checking because I didn't have a Mac. It has been updated. Please try downloading the latest version
