### ISSUE TITLE
Crowd Control ignores Temp Obstacles?

### ISSUE THREAD

**Issue by Chompetto** [ikpil/DotRecast#14]
When using Temp Obstacles in the Demo I am able to generate a correct path when leveraging a path for individual agents (Test Navmesh).
![image](https://github.com/ikpil/DotRecast/assets/4955517/d8ac181a-476e-401a-bbf6-54111901055e)

Crowd Control seems to ignore Temp Obstacles as shown by the path generated below and walks right through it.
Or is there a setting I am misconfiguring for Crowd Control for it to ignore Temp Obstacles?.
![image](https://github.com/ikpil/DotRecast/assets/4955517/099e4003-e464-498c-aeea-cfeaa8daeee5)

**Comment by ikpil** [comment]
It's fixed

Thank you for reporting the bug.
