### ISSUE TITLE
[Help] How can I get the indices of the generated navmesh?

### ISSUE THREAD

**Issue by Doprez** [ikpil/DotRecast#18]
I am finally working on integrating this into Stride3d and I am having trouble actually generating the mesh for debugging purposes. 

~As far as I can tell in your demos for Unity the methods used only require that the vertices are provided as far as I understand it. in the [Unity](https://github.com/ikpil/UniRecast/blob/e43c79fb1f1e61e9501ee4ef7aa25c34995cddde/src/UniRecast.Unity/Assets/Plugins/UniRecast/Editor/UniRcNavMeshSurfaceEditor.cs#L251C4-L251C4) example I see you are generating per poly but in my generated mesh some poly data has more than 3 points depending on the tile.~

I didnt realize `DrawAAConvexPolygon` was for drawing an arrow not the poly mesh.

![image](https://github.com/ikpil/DotRecast/assets/73259914/aa5c4e67-7810-40a7-bd11-0cfee3026258)

In the code above you can see one of the polys has 24 verts or 8 Vector3 points. am I just meant to try and make my own indices or is there a way to get that data from the navmesh?

**Comment by GabrielMotaAlexandre** [comment]
Isn't it `detailTris`?

**Comment by Doprez** [comment]
I took a break to work on some other things. I will give this a try soon as I am back to working on it.

I think the issue I had with detailTris is some of the data was wrong? there were indices that had a value of 700+ when the mesh was well below 100 vertices so it cause issues. Ill try again to make sure I didnt miss something, thank you!
