### ISSUE TITLE
Updates to Demo

### ISSUE THREAD

**Issue by adambennett55** [ikpil/DotRecast#31]
Would it even be possible to update the demo to make it more of a tool, in the sense where we could click to select single polygons in our generated navmesh and delete them, and if even possible an option to add or paint in new polygons?

**Comment by ikpil** [comment]
Yes, it is possible to enhance the demo into a more useful tool. However, as I am not a full-time open-source developer, my current focus is on porting recastnavigation. While I agree with the suggestions for enhancing the tool, there is currently no specific plan for those requests due to the ongoing prioritization of tasks. Further improvements for additional features may be considered later on. 

It seems like a similar functionality could be achieved using convex volumes.
Thank you.

![image](https://github.com/ikpil/DotRecast/assets/313821/143d2a4e-44fe-4005-8ea8-60a5a0b4cb14)

**Comment by adambennett55** [comment]
Hmm can convex volumes be added in the demo? I really like to do my stuff visually LOL

**Comment by ikpil** [comment]
Could you show me how you tested it by any chance? 

here's how it turned out for me

https://youtu.be/CPvc19gNUEk

or

https://github.com/ikpil/DotRecast/assets/313821/35625884-bc22-4230-9f4a-535c331821e2

**Comment by adambennett55** [comment]
Ok i figured out what i was doing wrong and this works great for removing obstacles and such that got meshed over anyways, BUT, Is there a way to make the navmesh mesh over a convex volume, there are some instances where it will miss a small section that i need it to path through like in the image, and i cant get it to do it. Would love the ability to have an add remove polygon tool, hehe!! I tried off mesh links and they just dont seem to work.

![Screenshot 2024-01-07 201535](https://github.com/ikpil/DotRecast/assets/29607848/e4f7b429-c9ed-4384-a5ed-7bc3eb91cf91)

**Comment by ikpil** [comment]
Generally, this issue can be addressed through the following steps. 

First, when creating the navigation mesh, areas with doors and those without doors should be crafted as separate meshes. 
Afterward, a "convex volume" should be added to the areas with doors to build the navigation mesh. 

During the game execution, you can load and control the navigation mesh, mesh without doors, mesh with doors, and other meshes as needed.

**Comment by adambennett55** [comment]
in that particular map i dont have access to open and close the doors, its a prebaked mesh, so i was hoping to somehow make it allow movement between the 2 spots at the door with a off mesh link, but i digress its not a huge probel i casn work around it, another question tho, is it somehow possible with convex volumes to make it mesh off the map with using a ground convex volume like in this picture? if so how is it done as its not working here.

![Uploading Screenshot 2024-01-10 205751.png…]()

**Comment by adambennett55** [comment]
![Screenshot 2024-01-10 205751](https://github.com/ikpil/DotRecast/assets/29607848/587434b4-2d2f-44ea-83c9-4bb9939001d3)

**Comment by ikpil** [comment]
Convex volumes set area type on the navmesh polygon, so if there is no navmesh polygon, they will not be set.

**Comment by adambennett55** [comment]
Ok good to know thx, I will add the connections in blender then first, tyvm for your help
