### ISSUE TITLE
Bug in Demo with Convex Volume Creation

### ISSUE THREAD

**Issue by adambennett55** [ikpil/DotRecast#34]
So when creating a convex volume, it will crash the program if you accidentally only give 3 points for the volume, is this intended behavior, and if so could if instead just catch the exception instead of crash the program? P.S. I made a new issue for this so it can be closed when acted on, separate from our ongoing discussion

**Comment by ikpil** [comment]
In any scenario, crashes should not occur. Could you provide me with relevant video footage, logs, and reproduction steps that I can review?

**Comment by adambennett55** [comment]
Real simple to reproduce, even happens in the sample geom, just open it up goto convex volumes, Click, move the mouse click again, move the mouse and double click it will always crash

**Comment by ikpil** [comment]
I have confirmed the bug. If it is fixed, I will mention it. Thank you.

**Comment by ikpil** [comment]
fix
