### ISSUE TITLE
Invert X axis

### ISSUE THREAD

**Issue by Danil0v3s** [ikpil/DotRecast#45]
Hey!

I've been using this mainly with Unity and it seems the X axis is inverted in comparison to Unity's coordinates. I have to do something like this every time I sent the position to my clients:

```cs 
public static SVector3 toSVector3(this RcVec3f v, RcVec3f mapSize) => new() { X = mapSize.X - v.X, Y = v.Y, Z = v.Z };
```

Is there any way you can think of to invert this so we can avoid these conversions?

**Comment by ikpil** [comment]
For use in Unity, I believe the method you mentioned is the best approach.

**Comment by Danil0v3s** [comment]
Yea, sounds reasonable. Thank you!
