### ISSUE TITLE
NuGet package(s)?

### ISSUE THREAD

**Issue by alexrp** [ikpil/DotRecast#5]
Hi!

I was just searching around to see if anyone had ported Recast/Detour to C# and came upon this project, which is looking great so far.

I just wanted to check if you're planning to publish it on NuGet for easier consumption?

**Comment by Doprez** [comment]
If it helps I personally use CircleCI for my personal projects [here](https://github.com/Doprez/Doprez.Stride/blob/master/.circleci/config.yml).

**Comment by ikpil** [comment]
@Doprez @alexrp 
I'm cautiously optimistic that I can package it next week or the week after.

**Comment by galvesribeiro** [comment]
Hello! Is there any updates on that matter? Thanks!

**Comment by ikpil** [comment]
I had more names to tidy up than I expected. Please wait a little longer.

**Comment by ikpil** [comment]
## Here!!
- https://www.nuget.org/packages/DotRecast.Recast.Toolset
