### ISSUE TITLE
Memcpy and heap allocations in DtCrowdTelemetry.Stop()

### ISSUE THREAD

**Issue by wrenge** [ikpil/DotRecast#51]
This causes the entire list to be copied over. It's pretty slow, if we going to do this every game cycle.
```cs
if (s.Count == TIMING_SAMPLES)
{
    s.RemoveAt(0);
}
```
This is Linq call and will cause memory allocation. Would be nice to avoid that, especially in a code that supposed to measure performance.
```cs
_executionTimings[name] = (long)s.Average();
```

I would replace List<T> with some sort of cyclic buffer to avoid removing elements and replace Linq query with foreach cycle or even SIMD.

**Comment by ikpil** [comment]
Merged! Thank you for your contribution! @wrenge
