### ISSUE TITLE
Demo cant create TileCaches

### ISSUE THREAD

**Issue by boris768** [ikpil/DotRecast#6]
In original recast nav demo, i can select "Temp obstacles" and create/save tile cache for future using. DotRecast, seems, has not that option in demo, but i see, that working with tile cache is present in the tests. Is DotRecast tile cache reader binary compatible with saved tile cache, generated by original recast? When i try to use reader, it crashes with exception "Could not allocate a tile".

**Comment by ikpil** [comment]
Hello.
Could you show me the sample code you tested?

**Comment by boris768** [comment]
> Hello. Could you show me the sample code you tested?

Same as in test TileCacheReader.cs
I generating tilecache on big mesh, if u need it, i can upload it.
Also i managed to save generated tilecache, and seems it can be readed as should.

**Comment by ikpil** [comment]
I have checked.
However, I am not reproducing the issue.
Please provide the reproducible executable code and the binary file used in the test.
You can provide the download link exclusively to me at ikpil0@gmail.com

**Comment by boris768** [comment]
> However, I am not reproducing the issue.
> Please provide the reproducible executable code and the binary file used in the test.
> You can provide the download link exclusively to

i resolved it by increasing DtNavMeshParams.maxTiles and DtNavMeshParams.maxPolys, it fixes that error on large obj.
