### ISSUE TITLE
Converting Unity navmesh to DtMeshData

### ISSUE THREAD

**Issue by nikita-one** [ikpil/DotRecast#76]
Hi. 
I want to use Unity's existing tooling for navmesh generation (basically for recast side of things), including off-mesh links and stuff. But I want to then use DotRecast's detour in a Unity-less environment. Is there an existing solution for this case? If not, any tips on how do I go about converting Unity navmesh data to DotRecast-supported format?

**Comment by ikpil** [comment]
I’ve received a similar question before. You might find some hints through this link.
- https://github.com/ikpil/UniRecast/issues/6

**Comment by nikita-one** [comment]
Cheers
